name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.5.1]
    env:
      NEXT_PUBLIC_OPENAI_API_KEY: ${{secrets.NEXT_PUBLIC_OPENAI_API_KEY}}
      NEXT_PUBLIC_PINECONE_API_KEY: ${{secrets.NEXT_PUBLIC_PINECONE_API_KEY}}
      NEXT_PUBLIC_PINECONE_INDEX_NAME: ${{secrets.NEXT_PUBLIC_PINECONE_INDEX_NAME}}
      NEXT_PUBLIC_PINECONE_NAMESPACE: ${{secrets.NEXT_PUBLIC_PINECONE_NAMESPACE}}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install --package-lock-only
      - run: npm ci
      - run: npm run build --if-present
      - name: Change Directory
        run: cd /home/latgoblab/actions-runner/_work/Libriary/Libriary
      - run: pm2 restart 0
